"""empty message

Revision ID: 133ac0702912
Revises: 
Create Date: 2019-06-15 14:11:02.976454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133ac0702912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='任务id'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='任务当前的状态'),
    sa.Column('result', sa.TEXT(), nullable=True, comment='任务执行的结果'),
    sa.Column('_traceback', sa.TEXT(), nullable=True, comment='报错信息'),
    sa.Column('create_time', sa.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('modified_time', sa.DATETIME(), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
