"""empty message

Revision ID: 541069b69ff5
Revises: c2c730fc2b73
Create Date: 2019-07-02 23:12:59.047754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541069b69ff5'
down_revision = 'c2c730fc2b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='任务id'),
    sa.Column('task_name', sa.String(length=300), nullable=True, comment='任务名字'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='任务当前的状态'),
    sa.Column('_result', sa.BLOB(), nullable=True, comment='任务执行的结果'),
    sa.Column('_traceback', sa.BLOB(), nullable=True, comment='报错信息'),
    sa.Column('create_time', sa.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('modified_time', sa.DATETIME(), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
