"""empty message

Revision ID: 58923b7ade76
Revises: 541069b69ff5
Create Date: 2019-07-06 18:28:56.334869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58923b7ade76'
down_revision = '541069b69ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_name', mysql.VARCHAR(length=300), nullable=True, comment='任务名字'))
    # ### end Alembic commands ###
