"""empty message

Revision ID: 9da393fd7dc7
Revises: 58923b7ade76
Create Date: 2019-07-06 18:29:27.910393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da393fd7dc7'
down_revision = '58923b7ade76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
